Added functionality to create state for redeem logic forward plugin
vyper-protocol/vyper-cli pull request #30
Opened 2022-10-28 10:23 UTC by iamakshat01

1. 
![image](https://user-images.githubusercontent.com/64827980/198565143-4181bc27-a0b0-4126-9266-ec8a5a8a5858.png)
2. Closes #29

2022-10-29 12:38 UTC, thegreat-vanderlinde requested changes
can we solve also the clippy warning?

2022-10-29 12:38 UTC, thegreat-vanderlinde commented on src/args/redeem_logic_plugin_args/redeem_logic_forward_args.rs
>  }
do you think we can easily have an interactive flow? where we can launch the create command and then the cli asks us the required parameters? in js we have [this](https://www.npmjs.com/package/inquirer) lib, just to give you an idea

2022-10-29 12:38 UTC, thegreat-vanderlinde commented on src/args/redeem_logic_plugin_args/redeem_logic_forward_args.rs
> +    /// notinal value for plugim
typo, should be plugin

2022-10-29 12:38 UTC, thegreat-vanderlinde commented on src/ops/redeem_logic_plugin_ops/redeem_logic_forward_ops.rs
> +                        ClientError::AnchorError(_) => println_error("Anchor not working"),
in case of `AnchorError` could be helpful to display the error message, should be included in the embedded object

2022-11-03 15:16 UTC, thegreat-vanderlinde commented on src/args/redeem_logic_plugin_args/redeem_logic_forward_args.rs
>  }
as discussed offline we can skip this for now

2022-11-07 14:18 UTC, iamakshat01 commented on src/args/redeem_logic_plugin_args/redeem_logic_forward_args.rs
> +    /// notinal value for plugim
Done

2022-11-07 14:19 UTC, iamakshat01 commented on src/ops/redeem_logic_plugin_ops/redeem_logic_forward_ops.rs
> +                        ClientError::AnchorError(_) => println_error("Anchor not working"),
Changed error handling to display the embedded object for all.

2022-12-06 13:28 UTC, thegreat-vanderlinde approved these changes

2022-12-06 13:28 UTC, merged