Added method to create rate-switchboard plugin
vyper-protocol/vyper-cli pull request #43
Opened 2022-12-14 07:48 UTC by iamakshat01

1. ![image](https://user-images.githubusercontent.com/64827980/207536446-6f13014f-c97d-493b-8ca7-2a398c78a58d.png)
2. Closes #41

2022-12-14 09:58 UTC, giacomo-cc requested changes

2022-12-14 09:58 UTC, giacomo-cc commented on src/main.rs
> +const SWITCHBOARD_AGG_MAINNET: &str = "7Y3nWv5B2rLiDBsNpkfXqa4cbJqszJos2sZVutF8R3FE";
the rate accounts are an input provided by the users, for example I can decide to provide [SOL/USD](https://switchboard.xyz/explorer/3/GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR) aggregator. please note that the user can provide up to 10 rate accounts

2022-12-15 06:43 UTC, iamakshat01 commented on src/main.rs
> +const SWITCHBOARD_AGG_MAINNET: &str = "7Y3nWv5B2rLiDBsNpkfXqa4cbJqszJos2sZVutF8R3FE";
Done
![image](https://user-images.githubusercontent.com/64827980/207791119-60ed287f-2d8e-42b9-bba8-cefd6fad17f1.png)

2022-12-15 09:02 UTC, thegreat-vanderlinde submitted a review, later dismissed
lgtm

2022-12-15 09:06 UTC, thegreat-vanderlinde approved these changes

2022-12-15 09:12 UTC, merged