Added create and fetch method for rate-pyth plugin
vyper-protocol/vyper-cli pull request #44
Opened 2022-12-14 08:57 UTC by iamakshat01

1. 
![image](https://user-images.githubusercontent.com/64827980/207551066-c5dfb8d1-f7d6-472c-b527-0e303a96403d.png)
2. Closes #39

2022-12-14 10:00 UTC, thegreat-vanderlinde requested changes

2022-12-14 10:00 UTC, thegreat-vanderlinde commented on src/main.rs
> +const PYTH_ORACLE_MAINNET: &str = "Gnt27xtC473ZT2Mw5u8wZ68Z3gULkSTb5DuxJy7eJotD";
same as switchboard, rate accounts are an user input

2022-12-14 10:00 UTC, thegreat-vanderlinde commented on src/main.rs
> +const DEVNET: &str = "https://api.devnet.solana.com";
can you provide some more meaningful name for this const? like `PUBLIC_DEVNET_RPC_ENDPOINT`

2022-12-15 06:55 UTC, iamakshat01 commented on src/main.rs
> +const DEVNET: &str = "https://api.devnet.solana.com";
Removing it.

2022-12-15 06:55 UTC, iamakshat01 commented on src/main.rs
> +const PYTH_ORACLE_MAINNET: &str = "Gnt27xtC473ZT2Mw5u8wZ68Z3gULkSTb5DuxJy7eJotD";
Done
![image](https://user-images.githubusercontent.com/64827980/207793195-3c48b360-b843-46a0-a3f0-3f5143ebe529.png)

2022-12-15 08:53 UTC, thegreat-vanderlinde approved these changes
lgtm

2022-12-15 08:53 UTC, merged