Added methods to find the version and tranche configuration
vyper-protocol/vyper-cli pull request #7
Opened 2022-09-28 11:27 UTC by iamakshat01

1. Implemented vyper --version. Closes #1.
2. Implemented vyper core fetch trancheId. Closes #6 
3. Used solana-cli-config to configuration. Closes #2 
4. Introduced console and clap. Closes #5 #4 
5. Working on having a progress bar while fetching tranche configuration.

2022-09-28 20:55 UTC, thegreat-vanderlinde requested changes

2022-09-28 20:55 UTC, thegreat-vanderlinde commented on src/ops/core_ops.rs
> +            println_name_value("version", &account.version);
can we format from this `version : [0, 1, 0]` to this `version: 0.1.0`

2022-09-28 20:55 UTC, thegreat-vanderlinde commented on src/ops/core_ops.rs
> +            println_name_value("tranche fair value", &account.tranche_data.reserve_fair_value);
here probably we have a wrong copy and paste, should be:
```rust
println_name_value("reserve fair value", &account.tranche_data.reserve_fair_value);
println_name_value("tranche fair value", &account.tranche_data.tranche_fair_value);
```

2022-09-28 20:55 UTC, thegreat-vanderlinde commented on src/ops/core_ops.rs
> +            println_name_value("tranche fair value", &account.tranche_data.reserve_fair_value);
for tranche and reserve fair values we're using under the hood [this library](https://docs.rs/rust_decimal/latest/rust_decimal/), serializing bytes on chain for anchor-compatibility (further reading [here](https://twitter.com/vanderlinde____/status/1564308344759656448?s=20&t=3P2qGBQt8KK_CuIEx0f5nw)). 

Can we try to deserialize decimal values with [Decimal::deserialize](https://docs.rs/rust_decimal/latest/rust_decimal/prelude/struct.Decimal.html#method.deserialize) transforming this:
```
reserve fair value : ReserveFairValue { value: [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], slot_tracking: SlotTracking { last_update: LastUpdate { slot: 163978618, _padding: [0, 0, 0, 0, 0, 0, 0, 0] }, stale_slot_threshold: 2 } } 
```
to this
```
reserve fair value : ReserveFairValue { value: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], slot_tracking: SlotTracking { last_update: LastUpdate { slot: 163978618, _padding: [0, 0, 0, 0, 0, 0, 0, 0] }, stale_slot_threshold: 2 } } 
```

2022-09-29 11:27 UTC, iamakshat01 commented on src/ops/core_ops.rs
> +            println_name_value("tranche fair value", &account.tranche_data.reserve_fair_value);
Ok

2022-09-29 11:27 UTC, iamakshat01 commented on src/ops/core_ops.rs
> +            println_name_value("tranche fair value", &account.tranche_data.reserve_fair_value);
Fixing

2022-09-29 11:28 UTC, iamakshat01 commented on src/ops/core_ops.rs
> +            println_name_value("version", &account.version);
Ok

2022-10-04 10:36 UTC, thegreat-vanderlinde approved these changes
looks good to me

2022-10-04 10:36 UTC, merged